version: '3.7'
services:
  mariadb:
    container_name: som_mariadb
    image: mariadb
    ports:
      - 3306:3306
    environment:
      MARIADB_DATABASE: som
      MARIADB_USER: som
      MARIADB_PASSWORD: a1234
      MARIADB_ROOT_PASSWORD: a1234
    networks:
      - backend
    restart: always

  redis:
    image: redis
    container_name: som_redis
    command: redis-server --port 6379
    hostname: redis
    ports:
      - 6379:6379
    restart: always


volumes:
  data: { }

networks:
  backend:
    name: backend
    driver: bridge
