version: '3.7'
services:
  mariadb:
    container_name: som_mariadb
    image: mariadb
    ports:
      - 3306:3306
    environment:
      MARIADB_DATABASE: som
      MARIADB_USER: som
      MARIADB_PASSWORD: a1234
      MARIADB_ROOT_PASSWORD: a1234
    networks:
      - backend
    restart: always


volumes:
  data: { }

networks:
  backend:
    name: backend
    driver: bridge
