version: '3.7'
services:
  mariadb:
    container_name: som_mariadb
    image: mariadb
    ports:
      - 3306:3306
    environment:
      MARIADB_DATABASE: som
      MARIADB_USER: som
      MARIADB_PASSWORD: a1234
      MARIADB_ROOT_PASSWORD: a1234
    networks:
      - backend
    restart: always

  redis:
    image: redis
    container_name: som_redis
    command: redis-server --port 6379
    hostname: redis
    ports:
      - 6379:6379
    restart: always

  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - 27017:27017
    volumes:
      - data:/data
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=a1234
    networks:
      - backend
    restart: always

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=a1234
      - ME_CONFIG_MONGODB_SERVER=mongodb
    networks:
      - backend

volumes:
  data: { }

networks:
  backend:
    name: backend
    driver: bridge

