version: '3.7'
services:
  mariadb:
    container_name: som_mariadb
    image: mariadb
    ports:
      - 3306:3306
    environment:
      MARIADB_DATABASE: som
      MARIADB_USER: som
      MARIADB_PASSWORD: a1234
      MARIADB_ROOT_PASSWORD: a1234
    networks:
      - backend
    restart: always

  redis:
    image: redis
    container_name: som_redis
    command: redis-server --port 6379
    hostname: redis
    ports:
      - 6379:6379
    restart: always

  elasticsearch:
    build:
      context: .
      args:
        VERSION: 7.17.3
    container_name: elasticsearch
    environment:
      - node.name=single-node
      - cluster.name=es-docker-cluster
      - discovery.type=single-node
      - xpack.security.enabled=true
      - xpack.security.audit.enabled=true
      - ELASTIC_PASSWORD=a1234
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - es-bridge

  kibana:
    image: docker.elastic.co/kibana/kibana:7.17.3
    container_name: kibana
    environment:
      SERVER_NAME: kibana
      ELASTICSEARCH_HOST: http://elasticsearch:9200
      ELASTICSEARCH_USERNAME: elastic
      ELASTICSEARCH_PASSWORD: a1234
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch
    networks:
      - es-bridge

volumes:
  data: { }

networks:
  backend:
    name: backend
    driver: bridge
  es-bridge:
    driver: bridge
